#!/bin/sh
case $1 in
	"up")
		playerctl volume 0.03+ ;;
	"down")
		playerctl volume 0.03- ;;
esac

vol=$(playerctl volume)
vol=${vol%0000*}
[ "$vol" = "1.00" ] && vol=100 || vol=${vol##*.}
dunstify -h string:x-dunst-stack-tag:songvol \
	-i "$HOME/.local/share/icons/Reversal-dark/actions/22/tools-rip-audio-cd.svg" \
	"Music" "Volume set to <b>$vol%</b>"
