#!/bin/sh
case $1 in
	"up")
           amixer sset Master 3%+
           state=$(amixer sget Master | grep "Left:") && state=${state#*[}
           dunstify -h string:x-dunst-stack-tag:sysvol -i "$HOME/.local/share/icons/Reversal-dark/status/22/audio-volume-high.svg" "Audio" "Volume set to <b>${state%%]*}</b>" ;;
	"down")
           amixer sset Master 3%- 
           state=$(amixer sget Master | grep "Left:") && state=${state#*[}
           dunstify -h string:x-dunst-stack-tag:sysvol -i "$HOME/.local/share/icons/Reversal-dark/status/22/audio-volume-low.svg" "Audio" "Volume set to <b>${state%%]*}</b>" ;;
	"mute")
           amixer sset Master toggle
           state=$(amixer sget Master | grep "Left:") && state=${state##*[}
           [ "${state%%]*}" = "on" ] && dunstify -h string:x-dunst-stack-tag:sysvol -i "$HOME/.local/share/icons/Reversal-dark/actions/22/player-volume.svg" "Audio" "Volume <b>Unmuted</b>" || dunstify -h string:x-dunst-stack-tag:sysvol -i "$HOME/.local/share/icons/Reversal-dark/status/22/audio-volume-muted-blocking-symbolic.svg" "Audio" "Volume <b>Muted</b>" ;; 
esac
